### ISSUE TITLE
RegistryConnector implementation differs from spec

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-registry-domain#21]
The implementation of the RegistryConnector differs from the spec at https://github.com/reTHINK-project/dev-service-framework/blob/master/docs/specs/messages/registration-messages.md   in the following aspects:

KeepAlive message:
- spec: update message with "body.resource"
- connector: expects "body.value.hypertyURL" and "body.value.hypertyDescriptorURL"

Advanced search:
- spec: defines "body.criteria" for search criterias
- implementation: expects "body.search"

**Comment by nunofmn** [comment]
Fixed in release 0.3.0 740550d.

**Comment by jboulmal** [comment]
The issue still persists, in the case of msg-node-nodejs.
The specs [read hyperty address by user](https://github.com/reTHINK-project/specs/blob/b0605876b5a3171040db79fc853099bd03697b2e/tests/msg-node/test/registration.spec.js#L118) like the following:
```
{
"id":"3",
"from":"hyperty-runtime://domain/runtime-1/registry",
"to":"domain://registry.domain",
"type":"read",
"body":{
"resource":"user://google.com/openIdTest10",
"attribute":"attribute"}
}
```
However the domain registry expects : ```icheckResourceType(msg.body.resource) === 'hyperty'``` in [RegistryConnector.js#L64](https://github.com/reTHINK-project/dev-registry-domain/blob/master/connector/src/RegistryConnector.js#L64)

**Comment by jboulmal** [comment]
In fact we get the following response from the registry domain:
`{ code: 404, description: 'Not Found' }`

Just notice that might help, during registration the response is :
`domain-registry          RamClient:77 - Created user user://google.com/openIdTest10 and hyperty hyperty://mydomain/4277e0a4-d333-495c-bafb-24fb834cff37`

**Comment by BernardoMG** [comment]
Hi @jboulmal . Can you please send me the content of the json used to register the Hyperty? I'll try to replicate

**Comment by jboulmal** [comment]
Hello @BernardoMG,

I got that erreur while performing [Message Node tests](https://github.com/reTHINK-project/specs/tree/b0605876b5a3171040db79fc853099bd03697b2e/tests/msg-node) on Msg-node-nodejs.

Concerning the Hyeprty, we have tried to `search hyperty address by user ` for [dtwebrtc](https://github.com/reTHINK-project/dev-hyperty/tree/master/src/dtwebrtc) in the testbeds of Orange. As result,  It cound't find it.

**Comment by jboulmal** [comment]
The `status` field is missing in the spec while registering the hyperty.
