### ISSUE TITLE
Not Found Responses not aligned with spec

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#23]
Not found responses looks currently like:

![image](https://cloud.githubusercontent.com/assets/3893553/17064635/63de49de-5035-11e6-9694-4a17283e09da.png)

that is not aligned with the [specs](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/specs/messages/registration-messages.md#registry-not-found-responses)

and it is causing errors in the core-runtime.

**Comment by nunofmn** [comment]
Fixed in release 0.3.0 740550d.

**Comment by pchainho** [comment]
It is still not fixed or it is back (develop branch)

**Comment by ruimangas** [comment]
I am not sure how this still happens. Not found messages are according to specs in all our branches. We need the exact scenario (logs, messages being sent) in which this is happening for us to try to reproduce and find the error.

**Comment by nunofmn** [comment]
Right now, the message node is overwriting the message code that comes from the domain registry connector.

https://github.com/reTHINK-project/dev-msg-node-vertx/blob/dev-address-reusage/src/main/java/eu/rethink/mn/component/RegistryConnector.java#L63

**Comment by pchainho** [comment]
@luistduarte pls have a look on this

**Comment by luistduarte** [comment]
Fixed on branch [dev-address-reusage](https://github.com/reTHINK-project/dev-msg-node-vertx/commit/4129a692f7667f813e8c8f4fc881866488cb2794)
